# Generated by Django 5.2.17 on 2026-09-30 20:37

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Имя')),
                ('slug', models.SlugField(unique=True, verbose_name='Адрес')),
                ('category', models.CharField(max_length=100, verbose_name='Категория')),
                ('description', models.TextField(blank=True, verbose_name='Описание программы')),
                ('availability', models.CharField(choices=[('available', 'Дату согласуем'), ('check', 'Доступность уточняйте'), ('unavailable', 'Временно недоступно')], default='available', max_length=20, verbose_name='Доступность')),
                ('is_listed', models.BooleanField(default=True, verbose_name='Показывать в каталоге')),
            ],
            options={
                'verbose_name': 'Персонаж',
                'verbose_name_plural': 'Персонажи',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ContactChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('phone', 'Телефон'), ('telegram', 'Telegram'), ('max', 'MAX')], max_length=20, unique=True, verbose_name='Канал')),
                ('label', models.CharField(max_length=150, verbose_name='Подпись')),
                ('url', models.CharField(max_length=500, verbose_name='Ссылка (https:// или tel:)')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Проверено владельцем')),
            ],
            options={
                'verbose_name': 'Канал связи',
                'verbose_name_plural': 'Каналы связи',
            },
        ),
        migrations.CreateModel(
            name='Offering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='Адрес')),
                ('kind', models.CharField(choices=[('animation', 'Анимация'), ('transformer', 'Большой герой + супергерой'), ('show', 'Шоу'), ('package', 'Пакет'), ('extra', 'Дополнение'), ('seasonal', 'Новый год')], max_length=20, verbose_name='Тип')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('duration_minutes', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Общее время, мин')),
                ('duration_is_approximate', models.BooleanField(default=False, verbose_name='Время приблизительное')),
                ('included_performers', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Исполнителей включено')),
                ('availability', models.CharField(choices=[('available', 'Дату согласуем'), ('check', 'Доступность уточняйте'), ('unavailable', 'Временно недоступно')], default='available', max_length=20, verbose_name='Доступность')),
                ('requirements', models.TextField(blank=True, verbose_name='Требования площадки')),
                ('is_listed', models.BooleanField(default=True, verbose_name='Показывать в каталоге')),
                ('characters', models.ManyToManyField(blank=True, to='catalog.character', verbose_name='Персонажи')),
            ],
            options={
                'verbose_name': 'Предложение',
                'verbose_name_plural': 'Предложения',
                'ordering': ['kind', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PackagePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Порядок')),
                ('title', models.CharField(max_length=150, verbose_name='Этап')),
                ('duration_minutes', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Время, мин')),
                ('is_approximate', models.BooleanField(default=False, verbose_name='Время приблизительное')),
                ('led_by_performer', models.BooleanField(default=True, verbose_name='Ведущие проводят программу')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='catalog.offering', verbose_name='Пакет')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='used_in_packages', to='catalog.offering', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Этап пакета',
                'verbose_name_plural': 'Этапы пакета',
                'ordering': ['position'],
                'constraints': [models.UniqueConstraint(fields=('package', 'position'), name='unique_package_part_position')],
            },
        ),
        migrations.CreateModel(
            name='PriceOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(verbose_name='Код тарифа')),
                ('label', models.CharField(max_length=150, verbose_name='Название тарифа')),
                ('context', models.CharField(choices=[('base', 'Основная цена'), ('with_animation', 'Шоу с анимацией'), ('second_performer', 'Доплата второго аниматора в пакете'), ('transformer_support', 'Второй участник: шоу после трансформера')], default='base', max_length=25, verbose_name='Условие')),
                ('amount_rub', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Цена, ₽')),
                ('duration_minutes', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Время тарифа, мин')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='Цена подтверждена')),
                ('terms', models.TextField(blank=True, verbose_name='Условия')),
                ('offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='catalog.offering', verbose_name='Предложение')),
            ],
            options={
                'verbose_name': 'Тариф',
                'verbose_name_plural': 'Тарифы',
                'ordering': ['offering', 'id'],
                'constraints': [models.UniqueConstraint(fields=('offering', 'code'), name='unique_offering_price_code'), models.CheckConstraint(condition=models.Q(('amount_rub__isnull', True), ('amount_rub__gt', 0), _connector='OR'), name='positive_price_amount'), models.CheckConstraint(condition=models.Q(('is_confirmed', False), ('amount_rub__isnull', False), _connector='OR'), name='confirmed_price_has_amount')],
            },
        ),
    ]
