# Generated by Django 5.2.17 on 2026-10-01 16:12

import catalog.media
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_new_year_duo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=catalog.media.character_photo_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), catalog.media.validate_photo_size], verbose_name='Фотография')),
                ('alt', models.CharField(help_text='Кратко опишите, что происходит на фото.', max_length=250, verbose_name='Описание фотографии')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('is_listed', models.BooleanField(default=True, verbose_name='Показывать на сайте')),
                ('source_key', models.CharField(blank=True, editable=False, max_length=500, null=True, unique=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='catalog.character', verbose_name='Персонаж')),
            ],
            options={
                'verbose_name': 'Фотография персонажа',
                'verbose_name_plural': 'Фотографии персонажей',
                'ordering': ['position', 'id'],
            },
        ),
    ]
