# Generated by Django 5.2.17 on 2026-10-01 16:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_characterphoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100, verbose_name='Имя клиента')),
                ('text', models.TextField(verbose_name='Текст отзыва')),
                ('source_label', models.CharField(default='Avito', max_length=100, verbose_name='Источник')),
                ('source_url', models.URLField(blank=True, verbose_name='Ссылка на источник')),
                ('source_key', models.SlugField(blank=True, editable=False, null=True, unique=True)),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('is_published', models.BooleanField(default=False, verbose_name='Показывать на сайте')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='Адрес')),
                ('excerpt', models.TextField(verbose_name='Краткое описание')),
                ('body', models.TextField(help_text='Абзацы разделяйте пустой строкой. Заголовки разделов начинайте с ##.', verbose_name='Текст статьи')),
                ('seo_title', models.CharField(blank=True, max_length=180, verbose_name='Заголовок для поиска')),
                ('seo_description', models.CharField(blank=True, max_length=300, verbose_name='Описание для поиска')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликовать')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Будущая дата откладывает появление статьи на сайте.', verbose_name='Дата публикации')),
                ('related_offering', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.offering', verbose_name='Предложить программу')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
                'ordering': ['-published_at', 'id'],
            },
        ),
    ]
