import Image from "next/image";
import Link from "next/link";
import { ArrowRight, ArrowUpRight, BadgeCheck, Clock3, Heart, MapPin, ShieldCheck, Sparkles } from "lucide-react";
import { getCharacters, getOfferings } from "@/lib/catalog";
import { CharacterCard, OfferingCard, PackageCard } from "@/components/cards";
import { SeasonalOffer } from "@/components/seasonal-offer";
import { OccasionCards } from "@/components/occasion-cards";
import { ChooseButton } from "@/components/choose-button";
import { basePrice, rubles } from "@/lib/types";

import { getReviews, getArticles } from "@/lib/editorial";
import { ReviewCards, ArticleCards } from "@/components/editorial-cards";

export const metadata = { alternates: { canonical: "/" } };
export default async function Home() {
  const [offerings, characters, reviews, articles] = await Promise.all([getOfferings(), getCharacters(), getReviews(), getArticles()]);
  const bumblebee = offerings.find(item => item.slug === "bumblebee");
  const featuredPackages = ["full-party", "sweet-vibe", "foam-party"].flatMap(slug => offerings.filter(item => item.slug === slug));
  const featuredCharacters = ["spider-man", "tiktok", "captain-america", "chase"].flatMap(slug => characters.filter(item => item.slug === slug));
  return <main id="main">
    <section className="hero container">
      <div className="hero-copy"><span className="eyebrow"><span className="tiny-star">✳</span> Маленькие гости. Большие впечатления.</span><h1>Праздник,<br />который дети<br /><span>не забудут.</span></h1><p>Любимые герои, настоящие трансформеры<br className="desktop-break" /> и шоу, от которых горят глаза.<br className="desktop-break" /> Приедем и устроим всё на вашей площадке.</p><div className="hero-actions"><ChooseButton>Подобрать праздник</ChooseButton><Link className="text-link" href="/transformers">Хочу трансформера <ArrowUpRight size={18} /></Link></div><div className="hero-guarantee"><span><ShieldCheck size={21} /></span><div><strong>Оплата после праздника</strong><p>Не понравится — можете не платить.</p></div></div></div>
      <div className="hero-art"><span className="hero-spark" aria-hidden="true">✳</span><div className="hero-photo"><Image sizes="(max-width: 900px) 100vw, 700px" src="/media/bumblebee-live.jpg" width="850" height="650" alt="Бамблби и увлечённые дети на настоящем празднике" fetchPriority="high" /><div className="photo-label"><i /> Вот ради этих глаз — всё и затеваем</div></div><div className="hero-sticker"><span>Осторожно:</span><strong>будет<br />восторг!</strong><Sparkles size={19} /></div><Link href="/transformers" className="hero-offer"><div><span>Бамблби + супергерой</span><strong>{bumblebee && basePrice(bumblebee) ? rubles(basePrice(bumblebee)!) : "Уточнить цену"} <small>/ 1 час</small></strong></div><span className="offer-arrow"><ArrowUpRight size={24} /></span></Link></div>
    </section>
    <div className="benefit-strip container"><span><MapPin size={20} /> Праздник там, где удобно вам</span><span><Heart size={20} /> Подход к детям от 2 до 16 лет</span><span><BadgeCheck size={20} /> Реальные костюмы на фотографиях</span></div>
    <section className="section container" id="transformers"><div className="section-head"><div><span className="eyebrow">Супергеройский масштаб</span><h2>Они большие.<br />Эмоции — <em>ещё больше.</em></h2></div><p>Трансформер и второй супергерой в одной программе. Игры, знакомства и фотографии, которые захочется пересматривать.</p></div><div className="offering-grid">{offerings.filter(item => item.kind === "transformer").map(item => <OfferingCard key={item.slug} offering={item} />)}</div><div className="section-note"><ShieldCheck size={19} /><span>Можно провести дома: заранее проверим потолки, проходы и свободное место.</span><Link href="/transformers">Как проходит программа <ArrowRight size={17} /></Link></div></section>
    <section className="packages-section"><div className="container section"><div className="section-head"><div><span className="eyebrow">Больше праздника, меньше хлопот</span><h2>Один пакет.<br /><em>Много «вау!»</em></h2></div><div><p>Уже собрали героя и шоу в готовые программы. Выбирайте по настроению, времени и бюджету.</p><Link className="text-link" href="/packages">Все 5 пакетов <ArrowUpRight size={18} /></Link></div></div><div className="package-grid">{featuredPackages.map(item => <PackageCard offerings={offerings} key={item.slug} offering={item} featured={item.slug === "full-party"} />)}</div><p className="package-footnote">Музыка после программы играет, пока команда собирает оборудование. На этом этапе ведущие уже не проводят игры.</p></div></section>
    <SeasonalOffer offering={offerings.find(item => item.slug === "new-year")} />
    <section className="section container"><div className="section-head"><div><span className="eyebrow">Кто сегодня придёт в гости?</span><h2>Любимый герой.<br /><em>Лично. На празднике.</em></h2></div><div><p>Супергерои, персонажи мультфильмов и игр. Найдём того, кого ваш ребёнок мечтает встретить.</p><Link href="/characters" className="text-link">Весь каталог персонажей <ArrowUpRight size={18} /></Link></div></div><div className="character-grid home-characters">{featuredCharacters.map((character, index) => <CharacterCard key={character.slug} character={character} index={index} />)}</div><div className="character-callout"><p>Сложно выбрать? Расскажите, чем увлекается ребёнок.</p><ChooseButton className="button outline">Помогите выбрать героя</ChooseButton></div></section>
    <section className="section container"><div className="section-head"><div><span className="eyebrow">Праздник объединяет</span><h2>Для всей группы.<br /><em>Для каждого ребёнка.</em></h2></div><p>Детский сад, выпускной или большое событие — найдём формат для вашей компании.</p></div><OccasionCards /></section>
    <section className="memory-section"><div className="container memory-layout"><div className="memory-copy"><span className="eyebrow">Такие моменты не придумаешь</span><h2>Сначала —<br /><em>«ничего себе!»</em><br />Потом —<br />«хочу ещё!»</h2><p>Наши костюмы, игры и настоящие праздники. Посмотрите, как это бывает у других семей.</p><Link href="/gallery" className="button navy">Посмотреть фотографии <ArrowUpRight size={18} /></Link></div><div className="memory-photos"><Image sizes="(max-width: 900px) 100vw, 700px" className="memory-one" src="/media/party-colour.jpg" alt="Весёлые игры с детьми на празднике" loading="lazy" width="600" height="450" /><Image sizes="(max-width: 900px) 100vw, 700px" className="memory-two" src="/media/party-friends.jpg" alt="Дети играют вместе с аниматором" loading="lazy" width="450" height="600" /><span className="memory-label">Вот оно, счастливое детство ✳</span></div></div></section>
    {reviews.length > 0 && <section className="section container"><div className="section-head"><div><span className="eyebrow">После праздника</span><h2>Родители рассказывают.</h2></div><Link className="text-link" href="/reviews">Все отзывы <ArrowUpRight size={18} /></Link></div><ReviewCards reviews={reviews.slice(0, 3)} /></section>}
    {articles.length > 0 && <section className="section container"><div className="section-head"><div><span className="eyebrow">Подготовимся вместе</span><h2>Праздник начинается с идеи.</h2></div><Link className="text-link" href="/articles">Все статьи <ArrowUpRight size={18} /></Link></div><ArticleCards articles={articles.slice(0, 3)} headingLevel={3} /></section>}
    <section className="section container faq-section"><div><span className="eyebrow">Родителям — спокойно</span><h2>Хороший праздник<br />начинается<br /><em>с понятных ответов.</em></h2><div className="guarantee-card"><ShieldCheck size={27} /><h3>Гарантия хорошего праздника</h3><p>Оплата после проведения.<br />Не понравится — можете не платить.</p></div></div><div className="faq-list">{[
      ["Где можно провести праздник?", "Дома, в кафе, детском саду, школе, детской студии, на природе или на улице — мы работаем на выезде. Игры подберём под вашу площадку, а условия проведения на открытом воздухе согласуем по сезону и погоде. Для трансформеров в помещении нужны потолки от 2,30 м, подходящие проходы и свободное место."],
      ["Если ребёнок стесняется?", "Начнём со спокойного знакомства и мягких игр. Темп увеличиваем постепенно, когда ребёнку комфортно включаться."],
      ["Сколько детей может участвовать?", "Работаем с компаниями от одного до 150 детей в разных форматах. Для большой группы подбираем число ведущих, игры и звук отдельно."],
      ["Можно добавить шоу к трансформерам?", "Да: азотное, серебряное шоу или сладкую вату. Обсудим последовательность и рассчитаем программу с учётом двух участников команды."],
      ["Выезд уже входит в цену?", "Для удалённых адресов, в том числе Весеннего и Южного, возможна доплата. Стоимость дороги уточним по адресу до заказа."],
    ].map(([question, answer]) => <details key={question}><summary>{question}<span>+</span></summary><p>{answer}</p></details>)}</div></section>
    <section className="container final-cta"><span className="cta-doodle" aria-hidden="true">✳</span><div><span className="eyebrow">Начнём с вашей идеи</span><h2>Какой праздник<br />придумаем <em>для вас?</em></h2><p>Расскажите о ребёнке. Остальное обсудим вместе.</p></div><ChooseButton className="button navy">Обсудить мой праздник</ChooseButton></section>
  </main>;
}
