server {
    listen 80;
    listen [::]:80;
    server_name mu56.ru www.mu56.ru;
    location ^~ /.well-known/acme-challenge/ { root /var/lib/letsencrypt; }
    location / { return 308 https://mu56.ru$request_uri; }
}
