server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name dev.mu56.ru;
    if ($host != dev.mu56.ru) { return 444; }
    location ^~ /.well-known/acme-challenge/ { root /var/lib/letsencrypt; }
    location / { return 308 https://dev.mu56.ru$request_uri; }
}
