import assert from 'node:assert/strict';
import {safeParams, safePath, track, ANALYTICS_CHOICE} from '../frontend/src/lib/analytics.ts';
import {FormJourney} from '../frontend/src/lib/form-journey.ts';
assert.deepEqual(safeParams({name:'Private Name',phone:'+70000000000',comment:'secret',date:'2026-11-01',query:'personal',program:'animation',hero:'harry-potter',status:429,seconds:Infinity}),{program:'animation',hero:'harry-potter',status:429});
assert.equal(safePath('/characters/harry-potter?phone=private#name'),'/characters/harry-potter');
assert.equal(safePath('/admin/leads/123'),null); assert.equal(safePath('/privacy'),null);
let consent='denied', calls=[];
globalThis.localStorage={getItem: key=>key===ANALYTICS_CHOICE?consent:null};
globalThis.window={location:{hostname:'mu56.ru',pathname:'/packages'},mu56AnalyticsReady:true,ym:(...args)=>calls.push(args)};
assert.equal(track('form_open'),false); consent='accepted'; assert.equal(track('form_open',{phone:'private',program:'animation'}),true);
assert.equal(calls.length,1); assert.equal(JSON.stringify(calls).includes('private'),false);
window.location.hostname='localhost'; assert.equal(track('form_open'),false); window.location.hostname='dev.mu56.ru'; assert.equal(track('form_open'),false);
window.location.hostname='mu56.ru'; window.mu56AnalyticsReady=false; assert.equal(track('form_open'),false);
let events=[], clock=1000;
const journey=new FormJourney((event,params)=>events.push({event,params}),()=>clock);
journey.open({program:'animation'}); journey.change('phone',true); journey.change('phone',true); clock=16000;
journey.invalid('data_consent'); journey.submit(); journey.error('network'); journey.submit(); journey.success(); journey.success(); journey.close('close');
assert.equal(events.filter(x=>x.event==='form_start').length,1); assert.equal(events.filter(x=>x.event==='contact_ready').length,1);
assert.equal(events.filter(x=>x.event==='form_progress' && x.params.field==='phone').length,1);
assert.equal(events.filter(x=>x.event==='lead_success').length,1); assert.equal(events.filter(x=>x.event==='form_abandon').length,0);
assert.equal(events.find(x=>x.event==='lead_success').params.attempt,2); assert.equal(events.find(x=>x.event==='lead_success').params.seconds,15);
journey.open({program:'unknown'}); journey.focus('phone'); journey.close('close'); journey.close('pagehide');
assert.equal(events.filter(x=>x.event==='form_abandon').length,1); assert.equal(events.at(-1).params.field,'phone'); assert.equal(events.at(-1).params.started,false);
journey.open({}); journey.change('offering'); journey.close('pagehide'); journey.resume(); journey.success(); journey.close('close');
assert.equal(events.filter(x=>x.event==='form_abandon').length,2); assert.equal(events.filter(x=>x.event==='lead_success').length,2);
console.log('Analytics: privacy filters, consent/domain gating, retries, success deduplication, abandon and resume passed.');
