# Generated by Django 5.2.17 on 2026-09-30 20:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Получена')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Имя клиента')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('contact_method', models.CharField(choices=[('phone', 'Звонок'), ('telegram', 'Telegram'), ('max', 'MAX')], default='phone', max_length=20, verbose_name='Способ связи')),
                ('messenger_handle', models.CharField(blank=True, max_length=150, verbose_name='Контакт мессенджера')),
                ('event_date', models.DateField(blank=True, null=True, verbose_name='Дата праздника')),
                ('event_time', models.TimeField(blank=True, null=True, verbose_name='Время в Оренбурге')),
                ('child_age', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Возраст ребёнка')),
                ('children_count', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Количество детей')),
                ('location', models.CharField(blank=True, max_length=300, verbose_name='Район / место')),
                ('comment', models.TextField(blank=True, max_length=2000, verbose_name='Пожелания клиента')),
                ('second_performer', models.BooleanField(default=False, verbose_name='Второй аниматор в пакете')),
                ('selection_snapshot', models.JSONField(default=dict, editable=False, verbose_name='Состав и тарифы на момент заявки')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('contacted', 'Связались'), ('proposal', 'Обсуждаем программу'), ('confirmed', 'Заказ согласован'), ('cancelled', 'Закрыта без заказа')], default='new', max_length=20, verbose_name='Статус')),
                ('manager_notes', models.TextField(blank=True, verbose_name='Внутренние заметки')),
                ('consent_at', models.DateTimeField(editable=False, verbose_name='Согласие получено')),
                ('consent_version', models.CharField(editable=False, max_length=50, verbose_name='Версия текста согласия')),
                ('notification_status', models.CharField(default='Бот ещё не подключён', editable=False, max_length=50, verbose_name='Уведомление в Telegram')),
                ('addons', models.ManyToManyField(blank=True, related_name='lead_addons', to='catalog.offering', verbose_name='Шоу и дополнения')),
                ('character', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.character', verbose_name='Выбранный герой')),
                ('offering', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.offering', verbose_name='Основная программа')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['-created_at'],
            },
        ),
    ]
