# Generated by Django 5.2.17 on 2026-10-01 17:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Ожидает отправки'), ('sending', 'Отправляется'), ('sent', 'Отправлено'), ('failed', 'Ошибка — нужен повтор'), ('uncertain', 'Доставка не подтверждена')], db_index=True, default='pending', max_length=20, verbose_name='Состояние')),
                ('attempts', models.PositiveIntegerField(default=0, verbose_name='Попыток')),
                ('next_attempt_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Следующая попытка')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Начало попытки')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Telegram подтвердил отправку')),
                ('message_id', models.BigIntegerField(blank=True, null=True, verbose_name='ID сообщения')),
                ('last_error', models.CharField(blank=True, max_length=200, verbose_name='Причина')),
                ('claim_token', models.UUIDField(editable=False, null=True)),
                ('lead', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_notification', to='leads.lead')),
            ],
            options={
                'verbose_name': 'Уведомление Telegram',
                'verbose_name_plural': 'Уведомления Telegram',
            },
        ),
    ]
