# Generated by Django 5.2.17 on 2026-10-03 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_new_year_formats'),
        ('leads', '0002_telegramnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='second_character',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='second_character_leads', to='catalog.character', verbose_name='Второй герой в пакете'),
        ),
    ]
